---
abstract: 'Load testdata into MySQL database'
author:
  - 'Takuya Tsuchida tsucchi@cpan.org'
build_requires:
  DBI: 0
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-DataLoader-MySQL
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  Test::mysqld: 0.11
requires:
  DBD::mysql: 0
  DBI: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.0.7
